# 站点基础配置
base_url = "https://ilikexff.cn"    # 站点基础URL（必须配置）
title = "八尺妖剑"                      # 站点标题
description = "简单是效率的灵魂"            # 站点描述
default_language = "zh"             # 默认语言（用于订阅源）
theme = "zhuia"                     # 使用的主题名称
output_dir = "public"               # 输出目录（默认public）
preserve_dotfiles_in_output = false # 是否保留输出目录中的点文件

# 编译选项
compile_sass = true  # 是否编译Sass文件
minify_html = false  # 是否压缩HTML输出
ignored_content = [] # 忽略的内容文件匹配规则
ignored_static = []  # 忽略的静态文件匹配规则

# 订阅源配置
generate_feeds = true                       # 是否生成订阅源
feed_filenames = ["rss.xml"]                # 订阅源文件名
hard_link_static = false                    # 是否对静态文件使用硬链接

# SEO配置
generate_sitemap = true    # 是否生成sitemap.xml
generate_robots_txt = true # 是否生成robots.txt

# 分类配置 - zhuia 主题支持标签和分类
taxonomies = [
    {name = "tags", render = true},
    {name = "categories", render = true},
]

# 搜索配置
build_search_index = false              # 是否构建搜索索引（中文暂不支持）

# Markdown渲染配置
[markdown]
highlight_code = true                 # 是否启用代码高亮
error_on_missing_highlight = false    # 缺失高亮语言是否报错
extra_syntaxes_and_themes = []        # 额外语法高亮目录
highlight_theme = "solarized-dark" # 代码高亮主题
render_emoji = false                  # 是否转换表情符号
external_links_class = ""             # 外部链接CSS类名
external_links_target_blank = false   # 外部链接是否新窗口打开
external_links_no_follow = false      # 是否添加nofollow
external_links_no_referrer = false    # 是否添加noreferrer
smart_punctuation = true              # 是否启用智能标点
definition_list = true                # 是否启用定义列表
lazy_async_image = true               # 是否启用图片懒加载
bottom_footnotes = true               # 脚注显示位置
insert_anchor_links = "none"          # 标题锚点链接位置

# 链接检查配置
[link_checker]
skip_prefixes = ["http://[2001:db8::]/"]        # 跳过的链接前缀
skip_anchor_prefixes = ["https://caniuse.com/"] # 跳过的锚点前缀
internal_level = "error"                        # 内部链接错误级别
external_level = "error"                        # 外部链接错误级别

# 多语言配置
[translations] # 默认语言翻译
[languages] # 多语言配置

# zhuia 主题配置
[extra]
# 博客名称
blog_name = "八尺妖剑"

# 订阅源文件名（兼容性）
feed_filename = "rss.xml"

# 页面内容最大宽度 (grid-xl 更宽)
grid_size = "grid-xl"

# 是否启用 KaTeX 数学公式渲染
katex = true

# 默认作者
author = "八尺妖剑"

# 显示选项
show_author = true
show_tags = true
show_categories = true
read_more_prompt = "阅读更多"
read_post_prompt = "阅读文章"

# 菜单配置
logo_image = "./assets/logo.png"
hamburger_menu = true

# 网站图标配置
favicon = "./assets/bachiico.ico"

# 主菜单项 - 已移除，使用打字效果替代
main_menu = []

# 页脚标语（包含备案信息）
footer_tagline = "简单是效率的灵魂 | 黔ICP备2021010295号"

# 启用自定义 CSS
custom_css = true

# 社交链接（您可以根据需要修改）
social_links = [
    # {url = "https://github.com/yourusername", name = "github"},
    # {url = "https://twitter.com/yourusername", name = "twitter"},
    # 取消注释并添加您的社交媒体链接
]

# 侧边栏配置
[extra.sidebar]
# 启用/禁用侧边栏
active = false

# 侧边栏文本片段
text_snippet = "欢迎来到<strong>八尺妖剑</strong>！这里分享技术文章和编程心得。"

# 作者信息
author_bio = "热爱编程，专注于技术分享和学习"
author_avatar = "avatar.png"

# 其他侧边栏选项
popular_tags = true
archive = true
related_posts = false
