# 根据 Zola 官方文档设置的 GitHub Pages 部署工作流
name: Build and Deploy Zola Site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # 获取子模块
          fetch-depth: 0    # 获取所有历史记录

      # 预处理 Markdown 文件，解决宏定义问题
      - name: Preprocess Markdown files
        run: |
          find content -name "*.md" -type f -exec sed -i \
            -e 's/fs/f_s/g' \
            -e 's/{{/{ {/g' \
            -e 's/}}/} }/g' \
            -e 's/{%/{ %/g' \
            -e 's/%}/% }/g' \
            {} \;

      # 使用 Zola 官方推荐的部署 Action
      - name: Build and Deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # 部署到 gh-pages 分支
          PAGES_BRANCH: gh-pages
          # 使用自动生成的 token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
