name: Build and Deploy Zola Site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Zola
        run: |
          curl -sL https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz | tar xz
          chmod +x zola
          sudo mv zola /usr/local/bin

      - name: Preprocess Markdown files
        run: |
          find content -name "*.md" -type f -exec sed -i \
            -e 's/fs/f_s/g' \
            -e 's/{{/{ {/g' \
            -e 's/}}/} }/g' \
            -e 's/{%/{ %/g' \
            -e 's/%}/% }/g' \
            {} \;

      - name: Build Zola site
        run: zola build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages
